name: workapp_backend
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  path: ^1.9.0
  postgres: ^3.5.9
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  intl: ^0.20.2
  shared_models:
    path: ../shared_models
  notes_repo_core:
    git:
      url: https://github.com/DanielWillforss/notes_repo_code.git
      ref: main
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
  mockito: ^5.4.4
  build_runner: ^2.4.6
